#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <zlib.h>
#include <stdbool.h>
#include "rno-g.h"

char * python = "python3"; //python interpreter
int entry = 0; //entry to plot
uint32_t mask = 0xffffff; //wf mask
char * ifile = NULL; //input file
bool keep = false; //keep the script 
char * save = NULL; // save waveforms to this, otherwise will be assumed interactive

int main(int nargs, char ** args) 
{

  bool found_entry = false;
  bool bad = false;
  for (int iarg = 1; iarg < nargs; iarg++)
  {
    if (!strcmp(args[iarg],"--python") && iarg < nargs - 1)
    {
      python = args[++iarg];
    }
    else if (!strcmp(args[iarg],"--mask") && iarg < nargs -1)
    {
      mask = strtoul(args[++iarg],NULL,0);
    }
    else if (!strcmp(args[iarg],"--save") && iarg < nargs -1)
    {
      save = args[++iarg];
    }
     else if (!strcmp(args[iarg],"--keep"))
    {
      keep = true;
    }
    else if (!ifile)
    {
      ifile = args[iarg];
    }
    else if (!found_entry)
    {
      entry = atoi(args[iarg]);
      found_entry = true;
    }
    else
    {
      bad = true;
    }
  }

  if (bad || !ifile || mask == 0)
  {
    fprintf(stderr,"Usage: rno-g-matplot-wf  [--keep] [--save SAVE] [--python PYTHON=python3] [--mask MASK] INPUTFILE [ENTRY=0]\n");
    fprintf(stderr,"    --keep          Don't delete the temporary python script\n");
    fprintf(stderr,"    --save SAVE     Save image to this file, otherwise assume interactive\n");
    fprintf(stderr,"    --python PYTHON python interpreter toouse (default python3) \n");
    fprintf(stderr,"    --mask MASK     Mask of channels to plot\n");
    fprintf(stderr,"    INFILE          Input file\n");
    fprintf(stderr,"    ENTRY           Entry to plot (default 0). Note that the raw format is serial so you have to loop through file until you find entry.\n");
    return 1;
  }

  rno_g_waveform_t wf;
  gzFile gf = gzopen(ifile,"r");

  rno_g_file_handle_t h = {.type = RNO_G_GZIP, .handle.gz = gf}; 

  int ientry = 0;
  while (rno_g_waveform_read(h, &wf) > 0)
  {
    if (ientry++ == entry)
    {
      break;
    }
  }

  gzclose(gf);

  if (entry >=ientry)
  {
    fprintf(stderr,"Asked for entry %d  but only %d in file\n", entry,ientry);
    return 1;
  }

  int nwf = __builtin_popcount(mask);
  int nrows = nwf <= 3 ? 1 :
              nwf <= 8 ? 2 :
              nwf <= 12 ? 3 :
              4;
  int ncols = (nwf + nrows-1) / nrows;

  printf("Plotting %d waveforms from entry %d of %s\n", nwf, entry, ifile);

  char * tmpfilenam = tempnam(NULL,"rnog-");

  FILE * f = fopen(tmpfilenam,"w");
  if (!f)
  {
    fprintf(stderr, "Couldn't open %s\n", tmpfilenam);
    return 1;
  }

  fprintf(f, "# Autogenerated\n");
  fprintf(f, "from matplotlib import pylab as plt\n");
  fprintf(f, "fig, axes = plt.subplots(%d,%d,sharex=True,sharey=True,figsize=(19.8,10.8))\n", nrows, ncols);

  int iplot = 0;
  for (int i = 0; i < 24; i++)
  {
    if ( ((1 << i ) & mask) == 0) continue;

    int row = iplot /ncols;
    int col = iplot % ncols;
    iplot++;

    fprintf(f,"axes[%d,%d].plot([", row,col);
    for (int j = 0; j  < wf.radiant_nsamples; j++)
    {
      fprintf(f, "%hd%c", wf.radiant_waveforms[i][j], j == wf.radiant_nsamples-1 ? ']' : ',');
    }
    fprintf(f,")\n");
    fprintf(f,"axes[%d,%d].set_title(\"CH %d\")\n\n",row,col, i);
  }

  fprintf(f,"plt.tight_layout()\n");

  if (save) fprintf(f,"fig.savefig(\"%s\")\n", save);
  else fprintf(f,"plt.show()\n");
  fclose(f);

  static char renamed[128];//surely big enough
  sprintf(renamed,"%s.py",tmpfilenam);

  rename(tmpfilenam, renamed);
  static char cmd[8192]; //surely big enough
  sprintf(cmd,"%s %s.py", python, tmpfilenam);
  int ret = system(cmd);
  if (!keep) unlink(renamed);
  else printf("As instructed, not deleting temporary script %s\n", renamed);

  if (ret)
  {
    fprintf(stderr,"Warning, script returned %d\n", ret);
  }
  if (save) 
  {
    printf("Output probably saved to %s\n", save);
  }

  return ret;
}
