BUILD_DIR=build
RNO_G_INSTALL_DIR?=/rno-g/
PREFIX?=$(RNO_G_INSTALL_DIR)
CC?=gcc
LIBDIR?=lib

VER_MAJOR=1
VER_MINOR=0
VER_REV=0

VERSUFFIX=$(VER_MAJOR).$(VER_MINOR).$(VER_REV)

.SECONDARY:

include config.mk

CFLAGS?=-Wall -Wextra -Og -g -std=gnu11
CFLAGS+= -I./src
CFLAGS+=$(EXTRA_CFLAGS)
CFLAGS+=-DRADIANT_SPI_SPEED=$(RADIANT_SPI_SPEED_MHZ)
CXXFLAGS?=-fPIC -Og -Wall -Wextra -g

LIBS=-lz -pthread

# macOS dylibs bake in their own load path (install name); without this it
# defaults to the relative build path (e.g. "build/librno-g.so.1.0.0"), which
# breaks dyld for any binary loading the library from outside that build dir.
ifeq ($(shell uname -s),Darwin)
LDFLAGS+=-install_name ${DESTDIR}$(PREFIX)/lib/$(notdir $@)
endif

ON_BBB?=no
ON_DIDAQ?=no

# are we (probably) on the BBB?
ifeq ($(shell uname -m),armv7l)
ON_BBB=yes
endif

ifeq ($(ON_BBB),yes)
$(info We are on the DAQ)
CFLAGS+=-mfpu=neon
CFLAGS+=-DON_BBB
DAQ_INCLUDES=src/radiant.h src/cobs.h src/adf4350.h src/flower.h src/rno-g-cal.h
endif



#check if inside rno-g-revn yocto build
ifneq (,$(filter ${MACHINE},rno-g-revn))
$(info We are inside yocto)
ON_DIDAQ=yes
endif

#check if on revn board
ifneq (,$(shell grep RevN /proc/device-tree/model 2> /dev/null))
$(info We are on the RevN DAQ)
ON_DIDAQ=yes
endif


#check if on revn board
ifeq ($(ON_DIDAQ),yes)
$(info We are building for the DiDAQ)
CFLAGS+= -DON_DIDAQ -DON_AM62X -DUSE_LIBGPIOS -DON_DIDAQ -I/usr/include -I${DESTDIR}${PREFIX}/include
LDFLAGS+=-L${DESTDIR}${PREFIX}/lib
GPIO_LIBS=-lgpios
DAQ_INCLUDES=src/rno-g-didaq.h src/rno-g-cal.h
endif

INCLUDES=src/rno-g.h src/rno-g-nsample-diff-hist.h

PYBIND_INCLUDES=$(shell python3 -m pybind11 --includes)

.PHONY: client daq didaq clean install install-daq install-rno-g-utils install-didaq client-py daq-py cppcheck test daq-test-progs rno-g-utils

client:  $(BUILD_DIR)/librno-g.so $(BUILD_DIR)/rno-g-version.h

daq: client $(BUILD_DIR)/libradiant.so  $(BUILD_DIR)/libflower.so $(BUILD_DIR)/librno-g-cal.so

didaq: client $(BUILD_DIR)/librno-g-cal.so $(BUILD_DIR)/librno-g-didaq.so

daq-test-progs:  $(addprefix $(BUILD_DIR)/test/, flower-configure-trigger flower-dump flower-equalize flower-set-thresholds flower-set-phased-thresholds flower-set-pps-delay\
	                  flower-status flower-trigger-enables flower-trigout-enables flower-wave radiant-check-trigger radiant-dump\
										radiant-scan radiant-threshold-scan radiant-try-daqstatus radiant-try-event radiant-try-ped cal-cmd)

rno-g-utils: $(BUILD_DIR)/test $(addprefix $(BUILD_DIR)/test/, rno-g-dump-ds rno-g-dump-hdr rno-g-dump-ped rno-g-dump-wf rno-g-wf-sample-diff-hists rno-g-wf-stats)

client-py: client $(BUILD_DIR)/rno_g.so
daq-py: daq client-py $(BUILD_DIR)/radiant.so

BLUE=\e[1;34m
RED=\e[1;31m
BOLD=\e[1m
GREEN=\e[1;32m
NC=\e[0m

$(shell printf "/*This file is auto-generated by the Makefile!*/\n#include \"rno-g.h\"\n\nconst char *  rno_g_get_git_hash() { return \"$$(git describe --always --dirty --match 'NOT A TAG')\";}" > src/rno-g-version.c.tmp; if diff -q src/rno-g-version.c.tmp src/rno-g-version.c >/dev/null 2>&1; then rm src/rno-g-version.c.tmp; else mv src/rno-g-version.c.tmp src/rno-g-version.c; fi)

## Super hacky test-suite :)
TESTS=test-cobs neon-test rno-g-test-didaq-chanmap
test: $(addprefix $(BUILD_DIR)/test/, $(TESTS) )
	@mkdir -p $(BUILD_DIR)/test-outputs/
	@let total=0 ; \
	let passed=0 ; \
	for test in $(TESTS) ; do \
 	echo -e "$(BLUE)Running test$(NC): $$test " ; \
 	let total++ ; \
	mkdir -p $(BUILD_DIR)/test-tmp/$$test ;\
	TEST_TMPDIR=$(BUILD_DIR)/test-tmp/$$test LD_LIBRARY_PATH+=:$(BUILD_DIR) $(BUILD_DIR)/test/$$test &> $(BUILD_DIR)/test-outputs/$$test ; \
	result=$$?; \
	if [ $$result -ne 0 ]; then \
	echo -e "$(RED)  FAILED (returned $$result)  $(NC)" ; \
	cat $(BUILD_DIR)/test-outputs/$$test ; \
	else  \
	echo -e '$(GREEN) PASSED $(NC)' ; \
	let passed++; \
	fi ; \
	done ; \
	echo -e "\n$(BOLD) $$passed/$$total tests passed$(NC)\n "


install: client
	install -d $(DESTDIR)$(PREFIX)/lib
	install -d $(DESTDIR)$(PREFIX)/include
	install $(BUILD_DIR)/librno-g.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g.so

	install $(INCLUDES) $(BUILD_DIR)/rno-g-version.h $(DESTDIR)$(PREFIX)/include/

install-daq: install $(BUILD_DIR)/libradiant.so $(BUILD_DIR)/libflower.so $(BUILD_DIR)/librno-g-cal.so
	install $(BUILD_DIR)/libradiant.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/libradiant.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/libradiant.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/libradiant.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/libradiant.so
	install $(BUILD_DIR)/libflower.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/libflower.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/libflower.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/libflower.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/libflower.so
	install $(BUILD_DIR)/librno-g-cal.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so
	install src/radiant.h src/flower.h src/rno-g-cal.h $(DESTDIR)$(PREFIX)/include/

install-didaq: install $(BUILD_DIR)/librno-g-didaq.so  $(BUILD_DIR)/librno-g-cal.so
	install $(BUILD_DIR)/librno-g-didaq.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-didaq.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-didaq.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-didaq.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-didaq.so
	install $(BUILD_DIR)/librno-g-cal.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/lib/
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VERSUFFIX) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VER_MAJOR)
	ln -sfr $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so.$(VER_MAJOR) $(DESTDIR)$(PREFIX)/$(LIBDIR)/librno-g-cal.so

	install src/rno-g-didaq.h src/rno-g-cal.h $(DESTDIR)$(PREFIX)/include/


ifeq ($(ON_BBB),yes)
	mkdir -p /data/test
	chown rno-g:rno-g /data/test
	ldconfig  # just put this here... doesn't seem to be needed on my laptop but mabye on BBB (Debian things?)
endif

install-rno-g-utils: rno-g-utils
	install -d ${DESTDIR}$(PREFIX)/bin
	install $(addprefix $(BUILD_DIR)/test/, rno-g-dump-ds rno-g-dump-hdr rno-g-dump-ped rno-g-dump-wf rno-g-wf-sample-diff-hists rno-g-wf-stats) ${DESTDIR}$(PREFIX)/bin/

clean:
	@echo Nuking $(BUILD_DIR) from orbit
	@ rm -rf $(BUILD_DIR)

$(BUILD_DIR):
	@ mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/test: $(BUILD_DIR)
	@ mkdir -p $(BUILD_DIR)/test

CLIENT_OBJS=rno-g.o rno-g-version.o rno-g-nsample-diff-hist.o rno-g-didaq-chanmap.o
$(BUILD_DIR)/librno-g.so.$(VERSUFFIX): $(addprefix $(BUILD_DIR)/, $(CLIENT_OBJS))
	@echo Linking $@
	@$(CC) -o $@ -shared -Wl,-soname,librno-g.so.$(VER_MAJOR) $(LDFLAGS) $^  $(LIBS)

RAD_OBJS=radiant.o cobs.o adf4350.o
$(BUILD_DIR)/libradiant.so.$(VERSUFFIX): $(addprefix $(BUILD_DIR)/, $(RAD_OBJS))
	@echo Linking $@
	@$(CC) -o $@ -shared $(LDFLAGS) $^  $(LIBS)

CAL_OBJS=rno-g-cal.o
$(BUILD_DIR)/librno-g-cal.so.$(VERSUFFIX): $(addprefix $(BUILD_DIR)/, $(CAL_OBJS))
	@echo Linking $@
	@$(CC) -o $@ -shared -Wl,-soname,librno-g-cal.so.$(VER_MAJOR) $(LDFLAGS) $^  $(LIBS)

FLWR_OBJS=flower.o
$(BUILD_DIR)/libflower.so.$(VERSUFFIX): $(addprefix $(BUILD_DIR)/, $(FLWR_OBJS))
	@echo Linking $@
	@$(CC) -o $@ -shared $(LDFLAGS) $^  $(LIBS)


RNOG_DIDAQ_OBJS=rno-g-didaq.o
$(BUILD_DIR)/librno-g-didaq.so.$(VERSUFFIX): $(addprefix $(BUILD_DIR)/, $(RNOG_DIDAQ_OBJS))
	@echo Linking $@
	@$(CC) -o $@ -shared -Wl,-soname,librno-g-didaq.so.$(VER_MAJOR) $(LDFLAGS) $^  $(LIBS) -ldidaq


# non-DAQ objects begin with rno-.... haas to be rno- instead of rno-g so that rno-g.c works :)
$(BUILD_DIR)/rno-%.o: src/rno-%.c $(INCLUDES) | $(BUILD_DIR)
	@echo Compiling non-DAQ object $@
	@$(CC) -c -fPIC -o $@ $(CFLAGS) $<

# except for rno-g-ididaq which is not a non-daq object
$(BUILD_DIR)/rno-g-didaq.o: src/rno-g-didaq.c $(INCLUDES) | $(BUILD_DIR)
	@echo Compiling DIDAQ object $@
	$(CC) -c -fPIC -o $@ $(CFLAGS) $<


$(BUILD_DIR)/rno_g.so:  src/rno-g-pybind.cc  $(INCLUDES) $(BUILD_DIR)/librno-g.so | $(BUILD_DIR)
	@echo Generating Python bindings for rno-g. This might take a while if you are on the BBB
	@c++ $(CXXFLAGS) -shared -std=c++11  $(PYBIND_INCLUDES) $< -o $@ -L$(BUILD_DIR) -lrno-g

$(BUILD_DIR)/radiant.so:  src/radiant-pybind.cc  $(INCLUDES) $(BUILD_DIR)/librno-g.so $(BUILD_DIR)/libradiant.so | $(BUILD_DIR)
	@echo Generating Python bindings for radiant. This might take a while if you are on the BBB
	@c++ $(CXXFLAGS) -shared -std=c++11 $(PYBIND_INCLUDES) $< -o $@ -L$(BUILD_DIR) -lrno-g -lradiant -lm

$(BUILD_DIR)/%.o: src/%.c $(DAQ_INCLUDES) | $(BUILD_DIR)
	@echo Compiling $@
	@$(CC) -c -fPIC -o $@ $(CFLAGS) $<

$(BUILD_DIR)/rno-g-version.h: Makefile
	@echo "Generating rno-g-version.h"
	@echo "#ifndef _RNO_G_VERSION_H" > $@
	@echo "#define _RNO_G_VERSION_H" >> $@
	@echo "#define RNO_G_VER_MAJOR $(VER_MAJOR)" >> $@
	@echo "#define RNO_G_VER_MINOR $(VER_MINOR)" >> $@
	@echo "#define RNO_G_VER_REV $(VER_REV)" >> $@
	@echo "#endif" >> $@

$(BUILD_DIR)/test/rno-g-%: test/rno-g-%.c $(INCLUDES) $(BUILD_DIR)/librno-g.so | $(BUILD_DIR)
	@echo Compiling $@
	$(CC)  -o $@  $(CFLAGS) -Isrc/  $< $(LDFLAGS) -L$(BUILD_DIR) -lrno-g -lz -lm

$(BUILD_DIR)/test/%: test/%.c $(INCLUDES) $(DAQ_INCLUDES) $(BUILD_DIR)/librno-g.so $(BUILD_DIR)/libradiant.so $(BUILD_DIR)/libflower.so $(BUILD_DIR)/librno-g-cal.so | $(BUILD_DIR)
	@echo Compiling $@
	@$(CC)  -o $@ $(CFLAGS) -Isrc/ $< $(LDFLAGS) -L$(BUILD_DIR) -lradiant -lrno-g -lflower -lrno-g-cal -lz -lm $(GPIO_LIBS)

$(BUILD_DIR)/test/%: test/%.py $(INCLUDES) $(DAQ_INCLUDES) $(BUILD_DIR)/librno-g.so  $(BUILD_DIR)/_rno_g.so $(BUILD_DIR)/libradiant.so | $(BUILD_DIR)
	ln  $@ $<

$(BUILD_DIR)/%.so: $(BUILD_DIR)/%.so.$(VER_MAJOR)
	ln -sf $(notdir $<) $@

$(BUILD_DIR)/%.so.$(VER_MAJOR): $(BUILD_DIR)/%.so.$(VERSUFFIX)
	ln -sf $(notdir $<) $@

cppcheck:
	cppcheck --enable=portability --enable=performance --enable=information  src

config.mk:
	@echo "Creating a default config.mk"
	@cat config.mk.default > $@
